### ISSUE TITLE
Generación PR

### ISSUE THREAD

**Issue by ivanfranco502** [nadiagutierrez89/TP-Curso.Net#1]
@nadiagutierrez89 queda pendiente la generación del PR para su corrección. Cualquier duda puntual sobre cómo generarlo, lo vemos por acá.

**Comment by nadiagutierrez89** [comment]
Hola Ivan, Buenas noches

Pude hacer que envíe los mails para las task vencidas a los usuarios, pero quise programar la ejecución de un Job que lo haga todos los días con el framework Quartz y no estaría funcionando.
Es decir programe el Job ExpiredTaskJob dentro del Scheduler que genere pero nunca esta recorriendo el Job cuando llega la hora de ejecución.
No pude encontrar el motivo, tienen idea de porque puede ser o que me estaría fallando?

Sino les parece que arme un punto de menú para el admin y que de esa forma mande los mails manualmente por la web?

Muchas gracias,
Nadia

**Comment by ivanfranco502** [comment]
@nadiagutierrez89, Dejá Quartz hasta donde pudiste, meté la opción de menú para envío manual y yo estos días voy a estar viendo lo del Job para que lo puedas implementar.

**Comment by nadiagutierrez89** [comment]
Gracias Ivan.

Enviado desde Yahoo Mail con Android 
 
  El lun., dic. 17, 2018 a 10:06, Iván Franco<notifications@github.com> escribió:   
@nadiagutierrez89, Dejá Quartz hasta donde pudiste, meté la opción de menú para envío manual y yo estos días voy a estar viendo lo del Job para que lo puedas implementar.

**Comment by ivanfranco502** [comment]
@nadiagutierrez89 estuve viendo y como lo más importante, estoy viendo que en ningún momento arrancas el scheduler de quartz en la app. Para esto tenés que instanciar el proceso de quartz en el Startup y ahí va a comenzar a ejecutarse dentro del proceso de la aplicación.

Te dejo un link con más detalle de cómo implementarlo (https://stackoverflow.com/questions/41821568/how-to-start-quartz-in-asp-net-core). Cualquier duda me avisas.

**Comment by nadiagutierrez89** [comment]
Hola Ivan, segui el jemplo de Stackoverflow pero no pude hacer funcionar el Quartz. Nunca se ejecutan los jobs. 
Así que cree un punto de menú para los usuarios Administrador (en este caso solo el admin@todo.local pass NotSecure123!!) puedan enviar los mails a demanda.
Se disparan las siguientes notificaciones por mail: Para tarea Vencida y próxima a vencerse dentro de 24 hs.
Ahora genero el PR.

Gracias,
Nadia

**Comment by ivanfranco502** [comment]
@nadiagutierrez89 perfecto, doy por cerrado el issue!
